# Generated by Django 5.1.4 on 2025-01-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NamesProjects', models.CharField(max_length=100)),
                ('DescriptionProjects', models.TextField()),
                ('SourceProjects', models.URLField()),
                ('LinkProjects', models.URLField()),
                ('ImageProjects', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
